name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "head"]
    env:
      # Released Bundler is broken on ruby-head due to ruby/ruby#16895.
      # Use Ruby's bundled Bundler until rubygems/rubygems#9529 is released.
      BUNDLER_VERSION: ${{ matrix.ruby == 'head' && '0' || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: ${{ matrix.ruby }}
      - name: Run tests
        shell: sh
        run: bundle exec rspec spec
